### ISSUE TITLE
Umbrella issue: command-line API

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#112]
### Rationale

There are two mainly used CLI tools in the melange distribution. I'd love to take some time to:

1. Rename them to be consistent with the `melange` name
2. Design a set of command line options that:
    1. are easier and more intuitive to use
    2. are POSIX compatible (e.g. long options with a single dash, aren't)

Related to:
- #85 

Right now is a good opportunity to break away from upstream, as Melange is still unreleased.

### Naming proposals:

I propose `mel` and `melc` for `bsb` and `bsc` replacements, respectively.

#### `mel`

`bsb` main tasks are: 
1. generating dune rules
2. shelling out to dune (after generating the rules)
3. initializing a project with `bsb -init` and `-theme` (related: https://github.com/melange-re/melange/issues/111)

I think we'd benefit from a subcommand API in the style of dune, esy and opam. I'm thinking something along the lines of:

```shell
$ mel rules # outputs the `dune.bsb` file, along with the `sourcedirs.json` meta data, same as `bsb -install`

$ mel build # same as `bsb -make-world`

$ mel clean # same as `bsb -clean-world`
```

`-init`, `-themes` and `-theme` go away.

#### `melc`

for `melc`, the situation is a little different. If Melange gets enough traction and gets to a point where dune integration is a reality, we'd benefit from keeping the command line arguments as close as possible to the OCaml [driver](https://github.com/ocaml/ocaml/blob/d10908cc514b2f6a6d79e2859549542d0c28a11b/driver/main_args.ml).

We can, however, take some time to rethink some options that we've inherited from ReScript. Specifically:

##### Remove

- `-bs-super-errors`: we don't use "super errors"
- `-bs-internal-check`: also unused

**Comment by coproduto** [comment]
I am in favor of this and I like the names `mel` and `melc` - however, can we keep `bsb` and `bsc` as aliases, at least for a while, so that people who are currently using `bsb` / `bsc` can use Melange as a drop-in replacement? I think making migration easier for current users is a good goal to pursue.

**Comment by anmonteiro** [comment]
I agree we should keep compatibility at least while people migrate. A few other thoughts:

- It's not clear to me how to keep (especially bsb) compatibility with the introduction of subcommands.
- Due to the way this project is architected, I don't think the breakage would be very problematic:
  - the `mel` / `bsb` commands are only used by the "toplevel" project. So even if dependencies haven't upgraded yet (or are using ReScript), we'll know how to build them.

**Comment by EduardoRFS** [comment]
Also related #119 

I think we should figure it out a couple of small breaking changes that we want to do to `bsc` so that when the migration happen we just keep the `bsc` compatible and `melc` is a new thing.

This will be the case for the `-format` which is probably `--convert` or `--print`. Also the behavior of `-o` is really weird and `bsc` currently reads the `bsconfig` which is also going to be a problem in the long run.

**Comment by EduardoRFS** [comment]
@Mathspy suggested us to make a thin wrapper, probably just a cmdliner cli mapping from old `bsc` to new `melc`

**Comment by anmonteiro** [comment]
done as of #243 and #284
