### ISSUE TITLE
unknown primitive building reason-nodejs

### ISSUE THREAD

**Issue by TheSpyder** [melange-re/melange#137]
```
File "/Users/spyder/work/myproject/_build/default/node_modules/reason-nodejs/src/BigInt.re", line 13, characters 0-39:
13 | external (%): (t, t) => t = "%modfloat";
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unknown builtin primitive "%modfloat"
```

The code [has been removed](https://github.com/sikanhe/reason-nodejs/commit/51ae0dbe92d660e3797a20b439def536b827820e#diff-686991b1c763e81ab10404ed47322e5c1590133ae1dd13ab260067165fd2c94e), but that change hasn't been released, and this error doesn't happen in ReScript.

**Comment by anmonteiro** [comment]
I just tried this with upstream ReScript, and I got the same error:

```
FAILED: src/Main.cmj

  1 │ Js.log2("Hello world", my_mod_float(5., 2.));
  2 │

  Unknown builtin primitive "%modfloat"
```

The difference seems to the following:

1. with ReScript, it only fails to compile when you _use_ the external
2. in Melange (I assume due to something having changed from 4.06 -> 4.12) we error eagerly if the declaration is present.

I find that the Melange behavior is the correct one here, and the most predictable. Hopefully the library can be released soon.

@TheSpyder I think there's nothing actionable to be done here. Do you think this can be closed?

**Comment by TheSpyder** [comment]
Oh interesting. Yeah I guess that's fair.
