### ISSUE TITLE
Quote directories passed to dune

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#169]
https://github.com/ocaml/dune/issues/4468

**Comment by EduardoAraujoB** [comment]
the line `180` of this file https://github.com/melange-re/melange/blob/077112fef7332670e11ede358e41b5ac1634b5b7/jscomp/bsb/bsb_ninja_gen.ml is causing the problem related to this [issue](https://github.com/ocaml/dune/issues/4468), the solution could be wrap the path with quotes, also could be good to check it out where the project have unicode paths and wrap it into a string

**Comment by anmonteiro** [comment]
I agree. We should audit all usages of `(dirs` and `(data_only_dirs` and quote all of them

**Comment by EduardoAraujoB** [comment]
So, tried to fix this issue, I quote some directories passed to dune, but I got a problem that I couldn't figure out how to solve or if it's related to dune
![image](https://user-images.githubusercontent.com/42449213/115608202-58111d00-a2bc-11eb-9f83-42900c417da3.png)
I could also up a branch on a fork with my changes

**Comment by EduardoAraujoB** [comment]
@anmonteiro I found a problem on the implementation of this issue, so on the generated dune file there is a `(progn` which contains the `-bs-package-output` with `commonjs:./src/subfolders:.bs.js` so the problem is without quoting the parameter passed to `-bs-package-output` the dune file will return errors with unicode directories (as the comment above),  but if I quote this to something like this `"commonjs:./src/subfolders:.bs.js"` then this problem will happens

![image](https://user-images.githubusercontent.com/42449213/120081394-d5863500-c093-11eb-9f11-0361fc34c68f.png)

I will update the PR with this changes

**Comment by anmonteiro** [comment]
Not relevant anymore with the dune integration coming soon.
