### ISSUE TITLE
cache emitted code to avoid duplicated work with multiple suffixes

### ISSUE THREAD

**Issue by EduardoRFS** [melange-re/melange#195]
Here we could cache most of the generated file, as the difference seems to be only in the header for ESM and CJS

https://github.com/melange-re/melange/blob/fork/jscomp/core/lam_compile_main.ml#L292

**Comment by jchavarri** [comment]
To expand with more details about this idea (this is mostly repeating what @EduardoRFS shared on Discord, just for doc purposes).

The idea to implement this "2-step" generation would be:

- at build time, generate `.js` files (in same objects dir as cmj?) that contain the module code, but not the imports / requires in headers
- at link time, promote the .js files by filling the "holes" in the headers including ES6 / CJS format + path to dependencies

Advantages:
- relocatable build artifacts as build-time `.js` would not rely on paths
- almost identical to ocamlc flow
- similar to what jsoo is doing as well
- maybe friendlier for dune cache?

Disadvantages:
- might take a perf hit on fresh builds due to split of 1-step into 2

**Comment by EduardoRFS** [comment]
The perf hit should be mostly from IO as we can run literally all files in the project in parallel.

What do you think @anmonteiro ?
