### ISSUE TITLE
build fails when there is a `data_only_dirs` already

### ISSUE THREAD

**Issue by tcoopman** [melange-re/melange#204]
if you have a `data_only_dirs` already in your dune file, the build fails because dune only allows 1.

**Comment by tcoopman** [comment]
Using `(dirs ...)` might be a workaround for some cases: https://dune.readthedocs.io/en/stable/dune-files.html#dirs-since-1-6

**Comment by aantron** [comment]
In reference to aantron/dream#85, what should Dream recommend? We want to exclude `node_modules` from being scanned by Dune. Should it be included while using Melange? Does Melange's `data_only_dirs` exclude `node_modules`? If not for both, should we then recommend using `dirs` in Dream? Or should Melange be fixed by merging `data_only_dirs` stanzas rather than creating a second one?

Thanks @tcoopman for the link to this issue.

**Comment by anmonteiro** [comment]
Not gonna solve this now that the dune integration is on the horizon. We won't be generating rules anymore with that flow.
