### ISSUE TITLE
Define conditional variable for output module format

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#257]
from @thespyder on discord:

> It depends on whether you’re using commonjs or es6 output. It’s extremely annoying that one external won’t work for both output styles if you want the default import object.

**Comment by ELLIOTTCABLE** [comment]
Okay. I spent the day spelunking and digging into this. Unfortunately, it's not as simple as it seems.

The core issue is that there can be *multiple* `module_system`s inside a single `Js_packages_info.t`. For example, let's take the following command-line:

```bash
$ melc -bs-package-name something \
   -bs-package-output es6:lib/esm_out:mjs \
   -bs-package-output commonjs:lib/cjs_out:cjs \
   something.ml
```

There's now two different output-files that need to be generated … with *different values* for `MEL_MODULE_FORMAT`. Okay, fine.

Unfortunately, all the existing machinery for conditional-compilation happens *at parse-time*, because of course it does. And currently, parse-time is *before* the iteration over the desired `Js_packages_info.t`.

> See that the `parser` for each filetype is invoked here, via `melc.ml:process_file`:
> 
> https://github.com/melange-re/melange/blob/dfa988c6/jscomp/core/js_implementation.ml#L189
> 
> … which *then* calls, after all of the conditional-variables have been evaluated, `Js_packages_info.iter`:
>
> https://github.com/melange-re/melange/blob/dfa988c6/jscomp/core/lam_compile_main.ml#L320

Of course, I can "lift" the iteration above the parsing — this would allow us to have a single `module_system` to inline into each AST. That's the easy solution, but costs a ton: literally doubles the time spent parsing, for any project producing both module-systems as output … which is most real-world projects.

(Alternatively, although it's much more complicated, one could theoretically leave part of the AST unevaluated, and then lazily collapse it at the last possible moment … quantum eigennodes. Hah. But that sounds like a *lot* of work.)

**Comment by TheSpyder** [comment]
I wouldn’t say _most_ projects use multiple simultaneous module output formats, but the one I worked on for two years did (it was recently able to switch to ES6 only).

**Comment by anmonteiro** [comment]
The changes in the 0.3.0 release (see [changelog](https://github.com/melange-re/melange/blob/main/Changes.md#030-2022-11-06)) effectively make this impossible to support.

To expand a little on it:
- for the dune integration, we're doing separate emission:
  1. compile `.cmj` without package-specs
  2. emit `.js` from the `.cmj`, and specify the `--bs-module-type {commonjs,es6}` flag here

So we won't know at AST-build time which package spec we're building for.
