### ISSUE TITLE
Improve description of Melange's position in the Reason/ReScript ecosystem

### ISSUE THREAD

**Issue by siemato** [melange-re/melange#301]
During onboarding, I was quite confused about Melange's goals. While the Readme states, that Melange is a ReScript fork, it only states the purpose of compiling Reason and OCaml to JS. It's worth mentioning, that there's a compatibility layer to ReScript and that Melange tries to stay compatible with it. My assumption initially was, that compatibility was dropped and I realized my mistake only after talking to people on Discord. The implications of making use of ReScript's ecosystem is substantial.

**Comment by anmonteiro** [comment]
I agree we should add something to the README noting as much.

However, I wouldn't say that we can making use of the _full_ ReScript ecosystem. While it's true we have a compatibility layer, and most ReScript packages work with Melange today, this is not a guarantee that we offer (especially because we're not in control of ReScript change).

**Comment by siemato** [comment]
#303 
not sure if 'compatibility layer' is the correct description. Fixed some stuff in the FAQ, 'being stuck on' sounds quite negative. I think I found a better way of describing the intent.

**Comment by anmonteiro** [comment]
Done in #303
