### ISSUE TITLE
migrate `bs.*` attributes to `mel.*` or `melange.*`

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#556]

**Comment by jchavarri** [comment]
One thing we have to consider when tackling this issue is what to do with the "namespace-less" attributes. Today, it's possible to use `[@module "foo"]` or `[@deriving abstract]`. I understand the only reason to keep supporting them is compatibility with existing ReScript binding libraries, but maybe we could attach some deprecation notice to them.

**Comment by EduardoRFS** [comment]
It is also possible to keep them as a special case in the ReScript syntax, by attaching an attribute to all ReScript attributes, similar to the one that exists for a couple Reason features, such that `%raw(x)` in OCaml becomes `([%raw x][@melange.rescript.extension])`

**Comment by anmonteiro** [comment]
Isn't it easier to convert them to namespaced ones in the rescript compat ppx?

**Comment by jchavarri** [comment]
Another one to think about is `[@bs]` attribute. I guess it could be renamed to just `@mel` or `mel.dot`. Can't be `mel.uncurry` because that one is used already and has different semantics.
