### ISSUE TITLE
Entry module is using named and default exports together

### ISSUE THREAD

**Issue by davesnx** [melange-re/melange#697]
While reading https://dev.to/psb/nextjs-the-app-router-and-reasonreact-2c0j I found a next issue specific that appears while using Melange.

The error message of this code is rather wrong which points to bsconfig stuff.

```
module Lola = {
  [@react.component]
  let make = () => {
    <div />;
  };
};

let default = Lola.make;
```

https://melange.re/unstable/playground/?language=Reason&code=bW9kdWxlIExvbGEgPSB7CiAgW0ByZWFjdC5jb21wb25lbnRdCiAgbGV0IG1ha2UgPSAoKSA9PiB7CiAgICA8ZGl2IC8%2BOwogIH07Cn07CgpsZXQgZGVmYXVsdCA9IExvbGEubWFrZTsK&live=off

**Comment by davesnx** [comment]
This issue is related with Fast refresh which https://forum.rescript-lang.org/t/rescript-nextjs-template-2021-update/829/25 is a good resource to understand the problem better

**Comment by jchavarri** [comment]
Simpler repro: https://melange.re/v1.0.0/playground/?language=OCaml&code=bGV0IGRlZmF1bHQgPSAx&live=off

Error message from rollup:

> Entry module "main.js" is using named and default exports together. Consumers of your bundle will have to use `MelangeApp.default` to access the default export, which may not be what you want. Use `output.exports: "named"` to disable this warning.

I think the problem is that Melange will include a `$$default` named export when using `default` id. We should allow users to use just the default export.

Explanation on why it's problematic to have both named and default exports: https://github.com/rollup/rollup/issues/1961#issuecomment-423037881.

**Comment by anmonteiro** [comment]
It looks like this is only a problem if you're consuming an ESM module from a CommonJS host (e.g. NodeJS). Is that true?

In that case, the warning seems pretty harmless to me, and I'm not sure if we should do anything about it.
