### ISSUE TITLE
Code generated for `mel.module` when using relative paths

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#750]
Following code

```ocaml
type nano

external nano : int -> nano = "nano" [@@mel.module]
```

Generates no output ([playground](https://melange.re/v2.0.0/playground/?language=OCaml&code=dHlwZSBuYW5vCgpleHRlcm5hbCBuYW5vIDogaW50IC0%2BIG5hbm8gPSAibmFubyIgW0BAbWVsLm1vZHVsZV0K&live=off)).

But this code (only the string in the external changes to local path):

```ocaml
type nano

external nano : int -> nano = "./nano" [@@mel.module]
```

Generates ([playground](https://melange.re/v2.0.0/playground/?language=OCaml&code=dHlwZSBuYW5vCgpleHRlcm5hbCBuYW5vIDogaW50IC0%2BIG5hbm8gPSAiLi9uYW5vIiBbQEBtZWwubW9kdWxlXQo%3D&live=off)):

```js
// Generated by Melange

import * as Nano from "./nano";

function nano(prim) {
  return Nano(prim);
}

export {
  nano ,
}
/* ./nano Not a pure module */
```

It's interesting, and there might be good reasons why it happens, I always assumed externals were a zero-code construct? Worst case we could at least document this behavior.

**Comment by anmonteiro** [comment]
the second case cannot be optimized away because melange wants to preserve the relative path invariant. `require('./nano')` is very different if it gets inlined into some other module which may not be in the same directory. 

I added a test to document this behavior in https://github.com/melange-re/melange/pull/901
