### ISSUE TITLE
Js__.Js_internal leaks into type errors and LSP diagnostics 

### ISSUE THREAD

**Issue by davesnx** [melange-re/melange#782]
Since Melange v2 with stdlib being wrapped on each package (https://github.com/melange-re/melange/pull/624) there's a few places where errors got worst.

```reason
let obj = Js.Obj.empty();
let _ = Shared_js.MelRaw.send(obj);
```

```
Line 4, 13:
Error This expression has type < .. > Js__.Js_internal.t
but an expression was expected of type string
``` 

## v2

https://melange.re/unstable/playground/?language=Reason&code=bGV0IHNlbmQgPSAob2JqOiBzdHJpbmcpID0%2BIFslbWVsLnJhdyAiZnVuY3Rpb24gKG9iaikgeyBjb25zb2xlLmxvZyhvYmopIH0iXTsKCmxldCBvYmogPSBKcy5PYmouZW1wdHkoKTsKbGV0IF8gPSBzZW5kKG9iaik7Cg%3D%3D&live=on

## v1

https://melange.re/v1.0.0/playground/?language=Reason&code=bGV0IHNlbmQgPSAob2JqOiBzdHJpbmcpID0%2BIFslYnMucmF3ICJmdW5jdGlvbiAob2JqKSB7IGNvbnNvbGUubG9nKG9iaikgfSJdOwoKbGV0IG9iaiA9IEpzLk9iai5lbXB0eSgpOwpsZXQgXyA9IHNlbmQob2JqKTsK&live=on

**Comment by jchavarri** [comment]
I don't see a way around this problem while keeping the library wrapped and maintaining the current layout with submodules like `Js.Null` being available.

Without `Js_internal`, there would be a circular dependency between `Js_null` and `Js`:
- `Js_null` depends on `Js` on different ways
  - The type alias `t` points to `Js.null`
  - The usage of uncurry `@u` resolves to `Js.Fn.arity1`
- On the other direction, `Js` depends on `Js_null` so that it gets exposed as `Js.Null`

Possible solutions could be:
- rename `Js_internal` to something shorter like `T`. In the end, it's not internal after all 😅 
- going back to the previous unwrapped version
- explore removing the dependency in the `Js_null` -> `Js` direction, by having the submodules define the "original" types and the ones in `Js` being aliases, and having the `@u` attribute be resolved directly to a new module `Js_fn`, that would also be exposed as part of the library.

Thoughts?

**Comment by davesnx** [comment]
Another possible solution is to have one big module similar on server-reason-react (https://github.com/ml-in-barcelona/server-reason-react/blob/main/packages/melange.js/js.ml)

**Comment by jchavarri** [comment]
That's really cool! Love that solution, so simple and solves all problems.

**Comment by jchavarri** [comment]
I tried to remove `Js_internal` by inlining everything in `Js` and got stuck at the point where `Caml_exceptions` depends on `Js_internal` but is not part of `Js`:

https://github.com/melange-re/melange/blob/1167ca745c7ddc2b950559e53d2ebe43585f3850/jscomp/runtime/caml_exceptions.ml#L75

I tried to fix but ran into some cyclic dependencies. 

Then I tried a different approach by adding a `js.mli` where `Js.t` is made abstract, but this breaks a lot of assumptions in the `##` ppx, as it will resolve to `unsafe_downgrade` which expects a `Js_internal`, but when `Js.t` is abstract the result of applying melange ppx doesn't type check. 

Needs more noodling...

**Comment by davesnx** [comment]
testAny should be public no?

**Comment by jchavarri** [comment]
i managed to fix some things following the 2nd approach I mentioned... see #798.

> testAny should be public no?

yes, it is public because `Js` includes `Js_internal`, but some things break if you make `Js.t` abstract.

**Comment by EduardoRFS** [comment]
@jchavarri if the issue is circular dependency between modules, maybe try -pack? It seems to help sometimes
